image: matteokjh/node-rsync-openssh:latest
#services:
#  - postgres

#after_script:
#  - rm secrets
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

stages:
  - build & deploy

job1:
  stage: build & deploy
  before_script:
  # - node -v
  # - npm config set registry https://registry.npm.taobao.org
  # - npm config ls -l
  # - npm install --timing
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # - npm run build
    # - pwd
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    # - ls
    # - mkdir "${HOME}/.ssh"
    # - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    # - rsync -arvz ./1.txt root@167.179.96.11:/home/www/sulpures.com
    - rsync -arvz -e 'ssh -i id_rsa' --rsync-path="sudo rsync" rsync ./1.txt root@167.179.96.11:/home/www/sulpures.com
  only:
    - master
  tags:
    - docker