image: node:latest
#services:
#  - postgres

#after_script:
#  - rm secrets
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

stages:
  - build
  - deploy

job1:
  stage: build
  before_script:
  - node -v
  - npm config set registry https://registry.npm.taobao.org
  - npm config ls -l
  - npm install --timing
  script:
    - pwd
    - npm run build
  only:
    - master
  tags:
    - shell

job2:
  stage: deploy
  before_script: 
    - ssh-keyscan 167.179.96.11 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ls
    - rsync -avr -e "ssh -i ~/.ssh/rsync_id.pub" ./dist/* root@167.179.96.11:/home/www/sulpures.com
  only:
    - master
  tags:
    - shell