image: node:latest
#services:
#  - postgres

#after_script:
#  - rm secrets
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

stages:
  - build
  - deploy

job1:
  stage: build
  before_script:
  - node -v
  - npm config set registry https://registry.npm.taobao.org
  - npm config ls -l
  - npm install --timing
  script:
    - npm run build
  only:
    - master
  tags:
    - docker

job2:
  stage: deploy
  before_script: 
    - pwd
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - ls
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    # - echo 123 >> 1.txt
  script:
    - rsync -arvz -e 'ssh -i id_rsa' ./1.txt root@167.179.96.11:/home/www/sulpures.com
  only:
    - master
  tags:
    - docker