image: node:latest
#services:
#  - postgres

before_script:
  - node -v
  - npm config set registry https://registry.npm.taobao.org
  - npm config ls -l
  - npm install --timing

#after_script:
#  - rm secrets
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - pwd
    - npm run build
  only:
    - master
  tags:
    - shell

job2:
  stage: deploy
  script:
    - ls
    - rsync ./dist/* root@167.179.96.11:/home/www/sulpures.com
  only:
    - master
  tags:
    - shell