image: node:latest
#services:
#  - postgres

before_script:
  - node -v
  - npm config set registry https://registry.npm.taobao.org
  - npm config ls -l

  - npm install --timing

#after_script:
#  - rm secrets
cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/

stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - pwd
    - ls
    - npm run build
    - echo 123 >> 1.txt
    - mv 1.txt /kjh
  only:
    - master
  tags:
    - docker

job2:
  stage: deploy
  script:
    - echo 1456 >> 2.txt
    - mv 2.txt /kjh
  only:
    - master
  tags:
    - docker